spring.application.name=eventhub
spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# conflitto con parole chiave
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# far avviare lo script SQL all'avvio dell'app per avere i ruoli da assegnare
spring.sql.init.mode=always

# altra proprieta per far partire lo script esattamente dopo la creazione delle tabelle
spring.jpa.defer-datasource-initialization=true

